-- Mod info config
Thai.StringUITable["Map Size:"] = "ขนาดแผนที่:"
Thai.StringUITable["Position:"] = "ตำแหน่ง:"
Thai.StringUITable["Default Zoom:"] = "ซูมเริ่มต้น:"
Thai.StringUITable["Update throttling:"] = "อัตราการอัปเดต:"
Thai.StringUITable["Close when open chest:"] = "ซ่อนเมื่อเปิดหีบ:"
Thai.StringUITable["Pause if focused:"] = "หยุดชั่วคราวขณะโฟกัส:"
Thai.StringUITable["Minimap's throttled updates per second, can help with FPS issues."] = "การอัปเดตแบบจำกัดต่อวินาทีของแผนที่ย่อสามารถช่วยแก้ปัญหา FPS ได้."
Thai.StringUITable["Throttling disabled, always keep map up-to-date"] = "ปิดใช้งานการควบคุม อัปเดตแผนที่อยู่เสมอ"
Thai.StringUITable["Update the map 10 times per second"] = "อัปเดตแผนที่ 10 ครั้งต่อวินาที"
Thai.StringUITable["Update the map 8 times per second"] = "อัปเดตแผนที่ 8 ครั้งต่อวินาที"
Thai.StringUITable["Update the map 6 times per second"] = "อัปเดตแผนที่ 6 ครั้งต่อวินาที"
Thai.StringUITable["Update the map 5 times per second"] = "อัปเดตแผนที่ 5 ครั้งต่อวินาที"
Thai.StringUITable["Update the map 4 times per second"] = "อัปเดตแผนที่ 4 ครั้งต่อวินาที"
Thai.StringUITable["Update the map 3 times per second"] = "อัปเดตแผนที่ 3 ครั้งต่อวินาที"
Thai.StringUITable["Update the map 2 times per second"] = "อัปเดตแผนที่ 2 ครั้งต่อวินาที"
Thai.StringUITable["Update the map every second"] = "อัปเดตแผนที่ทุกวินาที"
Thai.StringUITable["Update the map 4 times in 5 seconds"] = "อัปเดตแผนที่ 4 ครั้งใน 5 วินาที"
Thai.StringUITable["Update the map 2 times in 3 seconds"] = "อัปเดตแผนที่ 2 ครั้งใน 3 วินาที"
Thai.StringUITable["Update the map every 2 seconds"] = "อัปเดตแผนที่ทุกๆ 2 วินาที"
Thai.StringUITable["Update the map every 3 seconds"] = "อัปเดตแผนที่ทุกๆ 3 วินาที"
Thai.StringUITable["Update the map every 4 seconds"] = "อัปเดตแผนที่ทุกๆ 4 วินาที"
Thai.StringUITable["Update the map every 5 seconds"] = "อัปเดตแผนที่ทุกๆ 5 วินาที"
Thai.StringUITable["Update the map every 6 seconds"] = "อัปเดตแผนที่ทุกๆ 6 วินาที"
Thai.StringUITable["Update the map every 8 seconds"] = "อัปเดตแผนที่ทุกๆ 8 วินาที"
Thai.StringUITable["Update the map every 10 seconds"] = "อัปเดตแผนที่ทุกๆ 10 วินาที"
Thai.StringUITable["Update the map every 30 seconds"] = "อัปเดตแผนที่ทุกๆ 30 วินาที"
Thai.StringUITable["False"] = "ไม่"
Thai.StringUITable["True"] = "ใช่"

-- In game full config
Thai.StringUITable["Top Right"] = "บนขวา"
Thai.StringUITable["Top Left"] = "บนซ้าย"
Thai.StringUITable["Top Center"] = "บนกลาง"
Thai.StringUITable["Middle Left"] = "กลางซ้าย"
Thai.StringUITable["Middle Center"] = "กลาง"
Thai.StringUITable["Middle Right"] = "กลางขวา"
Thai.StringUITable["Bottom Left"] = "ล่างซ้าย"
Thai.StringUITable["Bottom Center"] = "ล่างกลาง"
Thai.StringUITable["Bottom Right"] = "ล่างขวา"

Thai.StringUITable["Custom Value"] = "กำหนดเอง"
Thai.StringUITable["Horizontal Scale:"] = "อัตราส่วนแนวนอน:"
Thai.StringUITable["Vertical Scale:"] = "อัตราส่วนแนวตั้ง:"
Thai.StringUITable["Show BG Image:"] = "แสดงพื้นหลัง:"
Thai.StringUITable["Map Blend Mode:"] = "โหมดแผนที่:"
Thai.StringUITable["BG Image Blend Mode:"] = "โหมดพื้นหลัง:"
Thai.StringUITable["Map Clickable:"] = "แผนที่คลิกได้:"
Thai.StringUITable["Map Transparency:"] = "ความโปร่งใส:"
Thai.StringUITable["BG Image Transparency:"] = "ความโปร่งใสพื้นหลัง:"
Thai.StringUITable["Button Scale:"] = "ขนาดปุ่ม:"
Thai.StringUITable["Toggle Button Show:"] = "แสดงปุ่มเปิด/ปิด:"
Thai.StringUITable["Toggle Button Vert Pos:"] = "ปุ่มเปิด/ปิดแนวตั้ง:"
Thai.StringUITable["Toggle Button Horiz Pos:"] = "ปุ่มเปิด/ปิดแนวนอน:"
Thai.StringUITable["Setting Button Show:"] = "แสดงปุ่มกำหนดค่า:"
Thai.StringUITable["Setting Button Horiz Pos:"] = "ปุ่มกำหนดค่าแนวนอน:"
Thai.StringUITable["Setting Button Vert Pos:"] = "ปุ่มกำหนดค่าแนวตั้ง:"
Thai.StringUITable["Save Button Show:"] = "แสดงปุ่มบันทึก:"
Thai.StringUITable["Save Button Horiz Pos:"] = "ปุ่มบันทึกแนวนอน:"
Thai.StringUITable["Save Button Vert Pos:"] = "ปุ่มบันทึกแนวตั้ง:"
Thai.StringUITable["Save"] = "บันทึก"
Thai.StringUITable["Toggle Minimap Key:"] = "ปุ่มสลับเปิด/ปิด:"
Thai.StringUITable["Toggle Minimap Key"] = "ปุ่มสลับเปิด/ปิด"
Thai.StringUITable["Center Character Key:"] = "ปุ่มปรับศูนย์กลาง:"
Thai.StringUITable["Center Character Key"] = "ปุ่มปรับศูนย์กลาง"
Thai.StringUITable["Setting Shotcut Key:"] = "ปุ่มตั้งค่า:"
Thai.StringUITable["Setting Shotcut Key"] = "ปุ่มตั้งค่า"

Thai.StringUITable["Setting"] = "ตั้งค่า"
Thai.StringUITable["Close Minimap"] = "ซ่อน"
Thai.StringUITable["Open Minimap"] = "แสดง"

Thai.StringUITable["0 (Most ZoomIn)"] = "0 (ซูมเข้ามากที่สุด)"
Thai.StringUITable["20 (Most ZoomOut)"] = "20 (ซูมออกมากที่สุด)"

Thai.StringUITable["Alpha Blended"] = "อัลฟ่าเบลนด์"
Thai.StringUITable["Additive"] = "อแดฟทิฟ"
Thai.StringUITable["Premultiplied"] = "คูณล่วงหน้า"
Thai.StringUITable["Inverse Alpha"] = "กลับอัลฟ่า"

Thai.StringUITable["Auto close minimap when open chest."] = "ปิดมินิแมพที่อัตโนมัติเมื่อเปิดหีบ"
Thai.StringUITable["Allow mouse click on minimap."] = "อนุญาตให้คลิกเมาส์บนมินิแมพ"
Thai.StringUITable["Size of Toggle Button, Config Button, Save Button on minimap."] = "ขนาดของปุ่มสลับเปิด/ปิด ปุ่มตั้งค่า ปุ่มบันทึกบนมินิแมพ"
